version: "3.9"

services:
  api:
    build: .
    container_name: goride_api
    ports:
      - "1026:1026"   # DRF API
      - "1025:1025"
    env_file:
      - core/.env
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    restart: unless-stopped
    user: root
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: goride_redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: goride_celery_worker
    command: celery -A core worker -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - core/.env
    depends_on:
      - api
      - redis
    restart: unless-stopped

  celery_beat:
    build: .
    container_name: goride_celery_beat
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/usr/src/app
    env_file:
      - core/.env
    depends_on:
      - api
      - redis
    restart: unless-stopped

  flower:
    build: .
    container_name: goride_flower
    env_file:
      - core/.env
    volumes:
      - .:/usr/src/app
    command: sh -c "sleep 5 && celery --broker=redis://redis:6379/0 flower"
    ports:
      - "5555:5555"
    depends_on:
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: goride_nginx
    ports:
      - "1027:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
      - ./media:/media
    depends_on:
      - api
    restart: unless-stopped

volumes:
  redis_data:
