x-common-setup: &common
  build: .
  env_file:
    - core/.env
  volumes:
    - .:/usr/src/app
  restart: unless-stopped

services:
  api:
    <<: *common
    container_name: goride_api
    command: bash start.sh
    ports:
      - "1026:1026"
      - "1025:1025"
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    user: root
    depends_on:
      - redis
    develop:
      watch:
        - path: .
          target: /usr/src/app
          action: sync
        - path: ./static
          target: /usr/src/app/static
          action: sync
        - path: ./media
          target: /usr/src/app/media
          action: sync

  redis:
    image: redis:alpine
    container_name: goride_redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery_worker:
    <<: *common
    container_name: goride_celery_worker
    command: celery -A core worker -l info
    depends_on:
      - api
      - redis

  celery_beat:
    <<: *common
    container_name: goride_celery_beat
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - api
      - redis

  flower:
    <<: *common
    container_name: goride_flower
    command: sh -c "sleep 5 && celery --broker=redis://redis:6379/0 flower"
    ports:
      - "5555:5555"
    depends_on:
      - api
      - redis

  nginx:
    image: nginx:stable-alpine
    container_name: goride_nginx
    ports:
      - "1027:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static
      - ./media:/media
    depends_on:
      - api
    restart: unless-stopped

volumes:
  redis_data:
