services:
    api:
        build: .
        container_name: goride_api
        ports:
            - "1026:1026"
            - "1025:1025"
        env_file:
            - core/.env
        volumes:
            - .:/usr/src/app
            - ./static:/usr/src/app/static
            - ./media:/usr/src/app/media
        restart: always
        user: root
        depends_on:
            - redis

    redis:
        image: redis:alpine
        container_name: goride_redis
        volumes:
            - redis_data:/data
        restart: always

    nginx:
        image: nginx:stable-alpine
        container_name: goride_nginx
        ports:
            - "1027:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./static:/static
            - ./media:/media
        depends_on:
            - api
        restart: always

volumes:
    redis_data: